name: Cloudflare Manual Delete Test

on:
  workflow_dispatch:

jobs:
  delete-list:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Run manual delete script
        run: node cf_test_manual_delete.js
